# Generated by Django 3.1.4 on 2020-12-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=5000)),
                ('comentario_final', models.CharField(max_length=5000)),
                ('clasificacion', models.CharField(max_length=50)),
            ],
        ),
    ]
