# Generated by Django 3.1.4 on 2020-12-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='clasificacion',
            field=models.SmallIntegerField(),
        ),
    ]
